### PR TITLE
Ajoute les comptes partagés

### PR DESCRIPTION
**Pull request by niladic**
Page de demande :
Screen Shot 2020-03-18 at 09 46 09

Page de réponse :
Screen Shot 2020-03-18 at 09 45 06

### CODE REVIEW

**Comment by jdauphant** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 7
           

Clones added
============
- app/controllers/UserController.scala  2
- app/controllers/CSVImportController.scala  1
- app/controllers/ApplicationController.scala  2
- app/serializers/UserAndGroupCsvSerializer.scala  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aplus/aplus/pullRequest?prid=5197723&bid=17047219)

**Comment by jdauphant** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 6
           

Coverage increased per file
===========================
+ app/controllers/ApplicationController.scala  7
         

Clones added
============
- app/serializers/UserAndGroupCsvSerializer.scala  1
- app/controllers/ApplicationController.scala  2
- app/controllers/CSVImportController.scala  1
- app/controllers/UserController.scala  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aplus/aplus/pullRequest?prid=5197723&bid=17047219)

**Comment by niladic** [comment]
@jdauphant j'ai passé plus d'une heure à tracker un truc qui marchait pas dans l'import csv, j'ai proposé `app/serializers/Keys.scala` qui m'aurais permis de ne jamais avoir ce problème en premier lieu.

**Comment by jdauphant** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 7
           

Coverage increased per file
===========================
+ app/controllers/ApplicationController.scala  7
         

Clones added
============
- app/controllers/ApplicationController.scala  2
- app/controllers/CSVImportController.scala  1
- app/controllers/UserController.scala  2
- app/serializers/UserAndGroupCsvSerializer.scala  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aplus/aplus/pullRequest?prid=5197723&bid=17047219)

**Comment by jdauphant** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 7
           

Coverage increased per file
===========================
+ app/controllers/ApplicationController.scala  6
         

Clones added
============
- app/controllers/ApplicationController.scala  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aplus/aplus/pullRequest?prid=5197723&bid=17047219)

**Comment by niladic** [comment]
J'ai supprimé l'étoile du champ signature Screen Shot 2020-03-19 at 12 44 20

**Pull request merged**
